### ISSUE TITLE
Советы по улучшению кода @sasa2002sasha

### ISSUE THREAD

**Issue by ananasn** [sasa2002sasha/lab2#1]
* Вопрос можно передавать как параметр `input('Какой жанр игр предпочитаете?\n')`
* Не нужно очищать файл, сразу открывайте его как `'w'`, а не на дозапись `'a'`. Он очистится перед открытием. 
* Можно работать с несколькими файлами, используя один контекстный менеджер.
```
with open('steam.csv', encoding='utf-8') as f, \
     open('result.txt', 'w', encoding='utf-8') as f2:
```
* По PEP8 в комментариях после октоторпа идет пробел
`# Are we at the top of the table?`

**Comment by Jyxerr** [comment]
Поправил
